version: '3'
services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: nchttp:latest
    ports:
    - "3000:3000"
    environment:
      OUTPUT2: "hello from nchttp@docker"
